algo = input('Digite Algo: ')
print('O tipo primitivo desse valor eh', type(algo))
print('É caixa alta',algo.isupper())
print('É letras minuscula',algo.islower())
print('É alpha numerico',algo.isnumeric())
print('Pode imprimir',algo.isprintable())
print('É ascII.',algo.isascii())
print('É variavele: ',algo.capitalize())